---

- name: deploy unattended-upgrade configuration
  template:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    src: ./templates/apt.conf.d/50unattended-upgrades.j2
    force: yes

- name: deploy auto-upgrade configuration
  template:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    src: ./templates/apt.conf.d/20auto-upgrades.j2
    force: yes

- name: create /etc/systemd/system/apt-* directory
  file:
    path: /etc/systemd/system/{{ item }}.d/
    state: directory
    mode: '0755'
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer
    - apt-daily-upgrade.service

- name: deploy timers
  include_tasks: deploy_timers.yml
  loop:
    - { name: 'apt-daily.timer', timer: 'update.timer' }
    - { name: 'apt-daily-upgrade.timer', timer: 'upgrade.timer' }

- name: deploy apt-upgrade service
  copy:
    src: apt/service_systemd
    dest: /etc/systemd/system/apt-daily-upgrade.service.d/override.conf
    force: yes
  notify:
    "reload daemon"
