---

# Monthly cron
- when: "auto_updates_upgrade_frequency == 'monthly'"
  block:
  - when: "ansible_distribution_major_version == '7'"
    name: create custom update cron for monthly (CentOS 7)
    cron:
      name: yum-cron update job for auto updates
      cron_file: yum-cron-update
      month: "*"
      job: "[ $(date '+\\%d') -ge {{ auto_updates_cron_min_day }} ] && \
         [ $(date '+\\%d') -le {{ auto_updates_cron_max_day }} ] && \
         /usr/local/bin/run_cron_update"
      user: root
      # Split to get hour and min from var
      minute: "{{ auto_updates_start_update_time.split(':')[1] }}"
      hour: "{{ auto_updates_start_update_time.split(':')[0] }}"
      state: present
      weekday: "{{ auto_updates_cron_week_day }}"

  - name: create custom upgrade cron for monthly
    cron:
      name: yum-cron upgrade job for auto updates
      cron_file: yum-cron-upgrade
      month: "*"
      job: "[ $(date '+\\%d') -ge {{ auto_updates_cron_min_day }} ] && \
         [ $(date '+\\%d') -le {{ auto_updates_cron_max_day }} ] && \
         /usr/local/bin/run_cron_upgrade"
      user: root
      # Split to get hour and min from var
      minute: "{{ auto_updates_start_upgrade_time.split(':')[1] }}"
      hour: "{{ auto_updates_start_upgrade_time.split(':')[0] }}"
      state: present
      weekday: "{{ auto_updates_cron_week_day }}"

# Weekly cron
- when: "auto_updates_upgrade_frequency == 'weekly'"
  block:
  - when: "ansible_distribution_major_version == '7'"
    name: create custom update cron for weekly (CentOS7)
    cron:
      name: yum-cron update job for auto updates
      cron_file: yum-cron-update
      month: "*"
      job: /usr/local/bin/run_cron_update
      user: root
      # Split to get hour and min from var
      minute: "{{ auto_updates_start_update_time.split(':')[1] }}"
      hour: "{{ auto_updates_start_update_time.split(':')[0] }}"
      state: present
      weekday: "{{ auto_updates_cron_week_day }}"

  - name: create custom upgrade cron for weekly
    cron:
      name: yum-cron upgrade job for auto updates
      cron_file: yum-cron-upgrade
      month: "*"
      job: /usr/local/bin/run_cron_upgrade
      user: root
      # Split to get hour and min from var
      minute: "{{ auto_updates_start_upgrade_time.split(':')[1] }}"
      hour: "{{ auto_updates_start_upgrade_time.split(':')[0] }}"
      state: present
      weekday: "{{ auto_updates_cron_week_day }}"

# Daily cron
- when: "auto_updates_upgrade_frequency == 'daily'"
  block:
  - when: "ansible_distribution_major_version == '7'"
    name: create custom update cron for daily (CentOS7)
    cron:
      name: yum-cron update job for auto updates
      cron_file: yum-cron-update
      month: "*"
      job: /usr/local/bin/run_cron_update
      user: root
      # Split to get hour and min from var
      minute: "{{ auto_updates_start_update_time.split(':')[1] }}"
      hour: "{{ auto_updates_start_update_time.split(':')[0] }}"
      state: present
      weekday: "{{ auto_updates_cron_days_daily }}"

  - name: create custom upgrade cron for daily
    cron:
      name: yum-cron upgrade job for auto updates
      cron_file: yum-cron-upgrade
      month: "*"
      job: /usr/local/bin/run_cron_upgrade
      user: root
      # Split to get hour and min from var
      minute: "{{ auto_updates_start_upgrade_time.split(':')[1] }}"
      hour: "{{ auto_updates_start_upgrade_time.split(':')[0] }}"
      state: present
      weekday: "{{ auto_updates_cron_days_daily }}"
