---

- when: ansible_distribution_major_version == '6'
  block:
    - name: remove all files (CentOS6)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/bin/needy-restart
        - /etc/sysconfig/yum-cron
        - /usr/local/bin/yum-cron
        - /usr/local/bin/run_cron_update
        - /usr/local/bin/run_cron_upgrade
        - /etc/cron.d/yum-cron-update
        - /etc/cron.d/yum-cron-upgrade
      notify:
        - "reload daemon"

    - name: remove packages (CentOS6)
      package:
        name: yum-cron
        state: absent

- when: ansible_distribution_major_version == '6' or ansible_distribution_major_version == '7'
  block:
    - name: remove all files (CentOS7)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/bin/needy-restart
        - /etc/yum/yum-cron.conf
        - /etc/yum/yum-cron-update.conf
        - /usr/local/bin/run_cron_update
        - /usr/local/bin/run_cron_upgrade
        - /etc/cron.d/yum-cron-update
        - /etc/cron.d/yum-cron-upgrade

    - name: remove packages (CentOS7)
      package:
        name: yum-cron
        state: absent

- when: ansible_distribution_major_version == '8'
  block:
    - name: remove all files (CentOS8)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/bin/needy-restart
        - /etc/dnf/automatic.conf
        - /etc/systemd/system/dnf-automatic-download.timer.d/
        - /etc/systemd/system/dnf-automatic-install.timer.d/
        - /etc/systemd/system/dnf-automatic-install.service.d/

    - name: remove packages (CentOS8)
      package:
        name: dnf-automatic
        state: absent
