#!/bin/bash

procs=$(lsof | grep -v "/dev/zero\|\[aio\]" | perl -lane 'print $F[0] if ($F[3] =~ /DEL|deleted/ && ! $seen{$F[0]}++)')
success=0

if [[ -z "$procs" ]]; then
    restart_result="Nothing to restart"
else
    services=$(ls /var/lock/subsys/ | grep "$procs")
    if [[ -z "$services" ]]; then
        restart_result="Nothing to restart"
    else
        restart_result="Restarting services:"
        nfs_restarted="false"
        for p in ${services}; do
            # don't touch ntpdate, it ntpd
            if [[ "$p" == "ntpdate" ]]; then
                continue
            fi
            # rpc.*** means nfs
            if [[ "$nfs_restarted" == "false" && ("$p" == "rpc.mountd" || "$p" == "rpc.statd" || "$p" == "rpc.idmapd") ]]; then
                p="nfs"
                nfs_restarted="true"
            fi
            restart_result="$restart_result\n  - $p"
            service_restart_result=$(service $p restart)
            if [[ "$?" == "0" ]]; then
                restart_result="$restart_result: ok"
            else
                restart_result="$restart_result: error restarting $p:\n$service_restart_result"
                success=1
            fi
        done
    fi
fi

# Manage restart error
echo -e "$restart_result"
if [[ $success -ne 0 ]]; then
    exit 1
fi

